apiVersion: v1
kind: Service
metadata:
  name: sphone-app
  namespace: sphone
  labels:
    app: sphone-app
spec:
  selector:
    app: sphone-app
  ports:
    - port: 80
      targetPort: 3000
      name: http
  type: ClusterIP
