apiVersion: v1
kind: ConfigMap
metadata:
  name: sphone-api-config
  namespace: sphone
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  Logging__LogLevel__Default: "Debug"
  Logging__LogLevel__Microsoft__EntityFrameworkCore__Database__Command: "Information"
