apiVersion: v1
kind: Service
metadata:
  name: sphone-api
  namespace: sphone
  labels:
    app: sphone-api
spec:
  selector:
    app: sphone-api
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
