apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - otel-collector/configmap.yaml
  - otel-collector/deployment.yaml
  - otel-collector/service.yaml
  - prometheus/configmap.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  - tempo/deployment.yaml
  - loki/deployment.yaml
  - grafana/deployment.yaml
