apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sphone-ingress
  namespace: sphone
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
    - hosts:
        - staging.sphone.example.com
      secretName: sphone-staging-tls
  rules:
    - host: staging.sphone.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sphone-api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sphone-app
                port:
                  name: http
