apiVersion: v1
kind: Service
metadata:
  name: sphone-zookeeper
  namespace: sphone
  labels:
    app: sphone-zookeeper
spec:
  selector:
    app: sphone-zookeeper
  ports:
    - port: 2181
      targetPort: 2181
      name: client
  clusterIP: None  # Headless for StatefulSet DNS
